spring:
  # H2 Driver
  datasource:
    url: jdbc:h2:tcp://localhost/~/trippy
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create # ??? create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6

server:
  servlet:
    encoding:
      charset: UTF-8