spring:
  # H2 Setting Info
  h2:
    console:
      enabled: true
      path: /h2-console  # H2 Console의 Path
  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:tcp://localhost/~/trippy # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password: 1234 # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)

#  datasource:
#    url: jdbc:oracle:thin:@ridetogetherdb_high?TNS_ADMIN=/home/ubuntu/scp/Wallet_RideTogetherDB
#    username: admin
#    password: Bdhor1EHGUS9910@
#    driver-class-name: oracle.jdbc.OracleDriver
#    data:
#      web:
#        pageable:
#          default-page-size: 20  #페이징 할 때 기본값, 20개씩 조회

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create # ??? create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        default_batch_fetch_size: 100
  profiles:
    include: jwt, oauth

server:
  8080

#logging:
#  level:
#    root: debug

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 클래스
#    url: jdbc:mysql://localhost:3305/trippydb?rewriteBatchedInserts=true
#    username: root  # MySQL 접속 계정
#    password: trippyzzang1234  # MySQL 접속 비밀번호
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect  # Hibernate MySQL Dialect 설정
#    show_sql: true
#    hibernate:
#      ddl-auto: update  # Hibernate DDL 자동 생성 설정 (create / update / validate 중 선택)
#  profiles:
#    include: jwt, oauth


#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6
#
#server:
#  servlet:
#    encoding:
#      charset: UTF-8


#jpa:
#  open-in-view: true
#  hibernate:
#    ddl-auto: create
#    naming:
#      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    use-new-id-generator-mappings: false
#  show-sql: true
#  properties:
#    hibernate.format_sql: true
#    dialect: org.hibernate.dialect.MySQL5InnoDBDialect

cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600